### ISSUE TITLE
Can't detect underscore in mention

### ISSUE THREAD

**Issue by ta1bbty** [cawfree/react-native-twitter-textview#10]
Hi @cawfree and @bjacog ,

Another good package of yours ( the other one I found useful was twitter native embed ).
The package seems to not properly detect `_` when in mention

![image](https://user-images.githubusercontent.com/45117337/90394842-0bcc6800-e0b1-11ea-9bab-f6eb67c66008.png)

This is the tweet link : https://twitter.com/_0nk4r_/status/1295171147936366593

and this is the tweet_text :
```
@impratikdabhi @trippy_bhaiya @harshbothra_ @manas_hunter @ADITYASHENDE17 @MrCyberwarrior @mrunal110 @darklotuskdb @vasim_infosec @aaditya_purani @udit_thakkur @iDiablo5 Note! People see that these guys making 8k a week and buying a phones, bikes and shit but they don't see they have also started from 0.They have invested shit ton of time and efforts  to get there. So new Fellas drop your $$$$ shit and work hard and persistent .#bugbountytip
```

**Comment by cawfree** [comment]
Thanks! I'll get this merged today. 🙏

**Comment by cawfree** [comment]
Aaand three weeks later, here we are. You have the patience of a saint, @ta1bbty. 🙏
[1.0.7](https://www.npmjs.com/package/react-native-twitter-textview/v/1.0.7)
