### ISSUE TITLE
Email address taken as mentions

### ISSUE THREAD

**Issue by Gabogg07** [cawfree/react-native-twitter-textview#3]
I am using the component for a description field. It works all fine for url and mentions, but when it comes to an email address it will only take the @gmail as a mention and ignore the rest of the address. 
Ex: myemail**@gmail**.com

**Comment by cawfree** [comment]
Hey @Gabogg07 , sorry for the delay getting back to you. I will work on implementing support for this tonight. ✌️

**Comment by cawfree** [comment]
Fixed in [1.0.4](https://github.com/cawfree/react-native-twitter-textview/commit/a0d8fea37ca2b275619a853225abc42005cb75eb). Thanks!
