### ISSUE TITLE
Skip line ignored after parsed text

### ISSUE THREAD

**Issue by Gabogg07** [cawfree/react-native-twitter-textview#4]
Hello, when the text contains any skip line character it gets ignored after the parse for finding mentions. 

Ex:
**Original Text**
Hello this is my first paragraph, it will be followed by a empty line.

Second paragrah is here!.

**Visible text**
Hello this is my first paragraph, it will be followed by a empty line.
Second paragrah is here!.

**Comment by cawfree** [comment]
Hey, thanks for getting in touch. Which version are you using?

**Comment by Gabogg07** [comment]
Hello @cawfree, i was using 1.0.3, just updated to 1.0.4 and realized this is already solved. Sorry for the issue and thanks for your reply

**Comment by cawfree** [comment]
Ah, that's great to hear. 👍
